version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  prolog-server:
    build:
      context: ../prolog
      dockerfile: Dockerfile
    container_name: prolog-server
    ports:
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379

volumes:
  mongo-data:

networks:
  app-network:
