openapi: 3.0.1
info:
  title: Ktor Film API
  description: API for managing films
  version: 1.0.0
paths:
  /films:
    get:
      summary: Retrieve all films
      responses:
        '200':
          description: A list of films
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'
    delete:
      summary: Delete all films
      description: Deletes all films from the database.
      responses:
        '200':
          description: Successfully deleted all films
        '500':
          description: Internal server error while attempting to delete films

  /film/{id}:
    get:
      summary: Get a film by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of a film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '400':
          description: Bad request

    delete:
      summary: Delete a film by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Film deleted successfully
        '400':
          description: Bad request

  /test/{number}:
    post:
      summary: Добавляет указ число рандомных записей
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Film updated successfully
        '400':
          description: Bad request

  /film/update:
    post:
      summary: Update a film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilmResponse'
      responses:
        '200':
          description: Film updated successfully
        '400':
          description: Bad request
  /film/add:
    post:
      summary: Add a new film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddingFilm'
      responses:
        '200':
          description: Film added successfully
        '400':
          description: Bad request

  /films/random:
    get:
      summary: Get random films
      description: Retrieve a list of random films filtered by genre.
      parameters:
        - name: size
          in: query
          required: true
          schema:
            type: integer
            description: Number of random films to retrieve
          description: The number of random films to retrieve.
        - name: genre
          in: query
          required: true
          schema:
            type: string
          description: The genre to filter the random films by.
      responses:
        '200':
          description: A list of random films
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The ID of the film
                    title:
                      type: string
                      description: The title of the film
                    genre:
                      type: string
                      description: The genre of the film
        '400':
          description: Bad request due to missing or invalid size parameter
        '404':
          description: No films found for the specified genre


components:
  schemas:
    Film:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - id
        - title

    FilmResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - id
        - title

    AddingFilm:
      type: object
      properties:
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - title