openapi: 3.0.1
info:
  title: Ktor Film API
  description: API for managing films
  version: 1.0.0
paths:
  /films:
    get:
      summary: Retrieve all films
      responses:
        '200':
          description: A list of films
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Film'

  /film/{id}:
    get:
      summary: Get a film by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of a film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        '400':
          description: Bad request

    delete:
      summary: Delete a film by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Film deleted successfully
        '400':
          description: Bad request

  /film/update:
    post:
      summary: Update a film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilmResponse'
      responses:
        '200':
          description: Film updated successfully
        '400':
          description: Bad request

  /film/add:
    post:
      summary: Add a new film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddingFilm'
      responses:
        '200':
          description: Film added successfully
        '400':
          description: Bad request

components:
  schemas:
    Film:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - id
        - title

    FilmResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - id
        - title

    AddingFilm:
      type: object
      properties:
        title:
          type: string
        director:
          type: string
        releaseYear:
          type: integer
      required:
        - title